<?php


namespace CoreFortress\Slider;


class Themes
{
    /**
     * Default Settings for "Full-Width Hero" Theme
     * @return array
     */
    public function getFullWidHeroThemeSettings()
    {
        return array(
                'background' => '#000000',
                'background_opacity' => 100,
                'border_size' => 0,
                'border_color' => '#000000',
                'border_style' => 'solid',
                'use_fixed_width' => false,
                'percent_width' => 100,
                'fixed_width' => 400,
                'use_fixed_height' => true,
                'fixed_height' => 800,
                'margin_top' => 20,
                'margin_right' => 0,
                'margin_bottom' => 20,
                'margin_left' => 0,
                'lazy_loading' => false,
                'content_pos_vertical' => 'center',
                'content_pos_horizontal' => 'center',
                'content_width_percent' => 30,
                'content_background_color' => '#FFFFFF',
                'content_background_opacity' => 0,
                'content_margin_top' => 0,
                'content_margin_right' => 0,
                'content_margin_bottom' => 0,
                'content_margin_left' => 0,
                'navigation_arrows' => true,
                'navigation_arrows_style' => 1,
                'title_font_size' => 24,
                'title_font_color' => '#ffffff',
                'title_margin_top' => 5,
                'title_margin_right' => 0,
                'title_margin_bottom' => 5,
                'title_margin_left' => 5,
                'title_border_size' => 0,
                'title_border_color' => '#FFFFFF',
                'title_border_style' => 'solid',
                'title_border_radius' => 0,
                'description_font_size' => 16,
                'description_font_color' => '#ffffff',
                'description_margin_top' => 5,
                'description_margin_right' => 0,
                'description_margin_bottom' => 5,
                'description_margin_left' => 5,
                'description_border_size' => 0,
                'description_border_color' => '#FFFFFF',
                'description_border_style' => 'solid',
                'description_border_radius' => 0,
                'cta_button_background_color' => '#0674ec',
                'cta_button_font_color' => '#FFFFFF',
                'cta_button_font_size' => 16,
                'cta_button_height' => 40,
                'cta_button_padding_horizontal' => 20,
                'cta_button_border_radius' => 5,
                'cta_button_margin_top' => 5,
                'cta_button_margin_right' => 0,
                'cta_button_margin_bottom' => 5,
                'cta_button_margin_left' => 5,
                'background_overlay' => true,
                'background_overlay_color' => '#000000',
                'background_overlay_opacity' => 70,
                'use_pagination' => true,
                'pagination_type' => 'bullets',
                'pagination_pos' => 'bottom',
                'pagination_background_color' => '#FFFFFF',
                'pagination_background_opacity' => 100,
                'pagination_active_background' => '#0674ec',
                'pagination_active_background_opacity' => 100,
                'use_thumbnails' => false,
                'thumbs_per_view' => 4,
                'thumbs_position' => 'bottom',
                'thumbs_height' => 100
        );
    }

    /**
     * Default Settings for "Product Showcase" Theme
     * @return array
     */
    public function getProductShowcaseThemeSettings()
    {
        return array(
            'background' => '#000000',
            'background_opacity' => 100,
            'border_size' => 0,
            'border_color' => '#000000',
            'border_style' => 'solid',
            'use_fixed_width' => false,
            'percent_width' => 100,
            'fixed_width' => 400,
            'use_fixed_height' => true,
            'fixed_height' => 400,
            'margin_top' => 20,
            'margin_right' => 0,
            'margin_bottom' => 20,
            'margin_left' => 0,
            'lazy_loading' => true,
            'content_pos_vertical' => 'top',
            'content_pos_horizontal' => 'right',
            'content_background_color' => '#000000',
            'content_background_opacity' => 40,
            'content_margin_top' => 50,
            'content_margin_right' => 50,
            'content_margin_bottom' => 0,
            'content_margin_left' => 0,
            'content_width_percent' => 25,
            'navigation_arrows' => false,
            'navigation_arrows_style' => 1,
            'title_font_size' => 20,
            'title_font_color' => '#FFFFFF',
            'title_margin_top' => 20,
            'title_margin_right' => 20,
            'title_margin_bottom' => 20,
            'title_margin_left' => 0,
            'title_border_size' => 0,
            'title_border_color' => '#FFFFFF',
            'title_border_style' => 'solid',
            'title_border_radius' => 0,
            'description_font_size' => 14,
            'description_font_color' => '#FFFFFF',
            'description_margin_top' => 0,
            'description_margin_right' => 20,
            'description_margin_bottom' => 20,
            'description_margin_left' => 0,
            'description_border_size' => 0,
            'description_border_color' => '#FFFFFF',
            'description_border_style' => 'solid',
            'description_border_radius' => 0,
            'cta_button_background_color' => '#FFFFFF',
            'cta_button_font_color' => '#000000',
            'cta_button_font_size' => 16,
            'cta_button_height' => 40,
            'cta_button_padding_horizontal' => 20,
            'cta_button_border_radius' => 0,
            'cta_button_margin_top' => 0,
            'cta_button_margin_right' => 20,
            'cta_button_margin_bottom' => 20,
            'cta_button_margin_left' => 0,
            'background_overlay' => true,
            'background_overlay_color' => '#000000',
            'background_overlay_opacity' => 10,
            'use_pagination' => true,
            'pagination_type' => 'fraction',
            'pagination_pos' => 'bottom',
            'pagination_background_color' => '#FFFFFF',
            'pagination_background_opacity' => 10,
            'pagination_active_background' => '#0674ec',
            'pagination_active_background_opacity' => 100,
            'use_thumbnails' => true,
            'thumbs_per_view' => 4,
            'thumbs_position' => 'bottom',
            'thumbs_height' => 100
        );
    }

    /**
     * Default Settings for "Minimalist" Theme
     * @return array
     */
    public function getMinimalistThemeSettings()
    {
        return array(
            'background' => '#FFFFFF',
            'background_opacity' => 100,
            'border_size' => 0,
            'border_color' => '#000000',
            'border_style' => 'solid',
            'use_fixed_width' => false,
            'percent_width' => 100,
            'fixed_width' => 400,
            'use_fixed_height' => true,
            'fixed_height' => 400,
            'margin_top' => 0,
            'margin_right' => 0,
            'margin_bottom' => 0,
            'margin_left' => 0,
            'lazy_loading' => false,
            'content_pos_vertical' => 'bottom',
            'content_pos_horizontal' => 'left',
            'content_background_color' => '#000000',
            'content_background_opacity' => 35,
            'content_margin_top' => 0,
            'content_margin_right' => 0,
            'content_margin_bottom' => 0,
            'content_margin_left' => 0,
            'content_width_percent' => 20,
            'navigation_arrows' => false,
            'navigation_arrows_style' => 7,
            'title_font_size' => 16,
            'title_font_color' => '#FFFFFF',
            'title_margin_top' => 10,
            'title_margin_right' => 0,
            'title_margin_bottom' => 10,
            'title_margin_left' => 20,
            'title_border_size' => 0,
            'title_border_color' => '#FFFFFF',
            'title_border_style' => 'solid',
            'title_border_radius' => 0,
            'description_font_size' => 12,
            'description_font_color' => '#FFFFFF',
            'description_margin_top' => 0,
            'description_margin_right' => 0,
            'description_margin_bottom' => 10,
            'description_margin_left' => 20,
            'description_border_size' => 0,
            'description_border_color' => '#FFFFFF',
            'description_border_style' => 'solid',
            'description_border_radius' => 0,
            'cta_button_background_color' => '#FFFFFF',
            'cta_button_font_color' => '#000000',
            'cta_button_font_size' => 16,
            'cta_button_height' => 40,
            'cta_button_padding_horizontal' => 20,
            'cta_button_border_radius' => 0,
            'cta_button_margin_top' => 0,
            'cta_button_margin_right' => 0,
            'cta_button_margin_bottom' => 10,
            'cta_button_margin_left' => 20,
            'background_overlay' => false,
            'background_overlay_color' => '#000000',
            'background_overlay_opacity' => 39,
            'use_pagination' => true,
            'pagination_type' => 'progressbar',
            'pagination_pos' => 'top',
            'pagination_background_color' => '#FFFFFF',
            'pagination_background_opacity' => 20,
            'pagination_active_background' => '#000000',
            'pagination_active_background_opacity' => 35,
            'use_thumbnails' => false,
            'thumbs_per_view' => 4,
            'thumbs_position' => 'bottom',
            'thumbs_height' => 100
        );
    }
    
}